### ISSUE TITLE
timeline breakdown refactor

### ISSUE THREAD

**Issue by mattsilv** [mattsilv/airport-time-estimator#30]
# Refactor Receipt Breakdown to Timeline View with Timestamps

## Overview

Transform the current "receipt-style" breakdown (showing time additions like +105 min, +45 min) into an intuitive timeline showing actual timestamps for each step of the airport journey.

**Current:** Time additions without context  
**Proposed:** Timeline with timestamps showing the logical flow from leaving home to boarding

## Example Timeline View

```
🚗 8:00 AM - Leave for airport
🛣️ 8:45 AM - Arrive at LAX
🅿️ 9:00 AM - Parking completed  
🧳 9:20 AM - Bag check completed
🔒 10:05 AM - Security/Immigration completed  
🍿 10:15 AM - Snacks acquired
⏰ 10:45 AM - Ready at gate (boarding begins)

Applied Modifiers:
• Anxiety Level 3 (adds buffer to security timing)  
• Kids Buffer 15% (extends total journey time)
```

### 1. Create Timeline Utility (`src/utils/timelineUtils.js`)

```javascript
/**
 * Timeline step configuration with logical order
 */
const TIMELINE_STEPS = {
  LEAVE_HOME: { 
    id: 'leave_home', 
    label: 'Leave for airport', 
    icon: '🚗', 
    order: 1,
    type: 'sequential'
  },
  TRAVEL_TIME: { 
    id: 'travel_time', 
    label: 'Travel to airport', 
    icon: '🛣️', 
    order: 2,
    type: 'duration'
  },
  ARRIVE_AIRPORT: { 
    id: 'arrive_airport', 
    label: 'Arrive at {airport}', 
    icon: '✈️', 
    order: 3,
    type: 'sequential'
  },
  PARKING: { 
    id: 'parking', 
    label: 'Parking completed', 
    icon: '🅿️', 
    order: 4,
    type: 'conditional'
  },
  CHECK_BAGS: { 
    id: 'check_bags', 
    label: 'Bag check completed', 
    icon: '🧳', 
    order: 5,
    type: 'conditional'
  },
  SECURITY: { 
    id: 'security', 
    label: 'Security/Immigration completed', 
    icon: '🔒', 
    order: 6,
    type: 'sequential'
  },
  SNACKS: { 
    id: 'snacks', 
    label: 'Snacks acquired', 
    icon: '🍿', 
    order: 7,
    type: 'conditional'
  },
  TSA_ARGUMENT: { 
    id: 'tsa_argument', 
    label: 'TSA discussion resolved', 
    icon: '🗣️', 
    order: 8,
    type: 'conditional'
  },
  READY_TO_BOARD: { 
    id: 'ready_to_board', 
    label: 'Ready at gate (boarding begins)', 
    icon: '⏰', 
    order: 9,
    type: 'sequential'
  }
};

/**
 * Calculate timeline with timestamps working backwards from boarding time
 */
export function calculateTimeline(formValues, selectedDate) {
  const boardingTime = parseTimeString(formValues.boardingTime);
  const boardingDate = new Date(selectedDate);
  boardingDate.setHours(boardingTime.hours, boardingTime.minutes);
  
  const steps = [];
  const modifiers = [];
  let currentTime = new Date(boardingDate);
  
  // Work backwards from boarding time
  // 1. Ready to board (boarding time)
  steps.unshift({
    ...TIMELINE_STEPS.READY_TO_BOARD,
    timestamp: formatTime(currentTime),
    isDestination: true
  });
  
  // 2. TSA argument (if selected)
  if (formValues.tsaArgument) {
    currentTime.setMinutes(currentTime.getMinutes() - 3);
    steps.unshift({
      ...TIMELINE_STEPS.TSA_ARGUMENT,
      timestamp: formatTime(currentTime),
      minutes: 3
    });
  }
  
  // 3. Snacks (if selected)
  if (formValues.needSnacks) {
    currentTime.setMinutes(currentTime.getMinutes() - 10);
    steps.unshift({
      ...TIMELINE_STEPS.SNACKS,
      timestamp: formatTime(currentTime),
      minutes: 10
    });
  }
  
  // 4. Security (includes base buffer + international + TSA pre + anxiety)
  const securityTime = calculateSecurityTime(formValues);
  currentTime.setMinutes(currentTime.getMinutes() - securityTime);
  steps.unshift({
    ...TIMELINE_STEPS.SECURITY,
    timestamp: formatTime(currentTime),
    minutes: securityTime,
    breakdown: getSecurityBreakdown(formValues)
  });
  
  // 5. Check bags (if selected)
  if (formValues.checkingBags) {
    currentTime.setMinutes(currentTime.getMinutes() - 20);
    steps.unshift({
      ...TIMELINE_STEPS.CHECK_BAGS,
      timestamp: formatTime(currentTime),
      minutes: 20
    });
  }
  
  // 6. Parking (if selected)
  if (formValues.needParking) {
    currentTime.setMinutes(currentTime.getMinutes() - 15);
    steps.unshift({
      ...TIMELINE_STEPS.PARKING,
      timestamp: formatTime(currentTime),
      minutes: 15
    });
  }
  
  // 7. Arrive at airport
  const airportCode = formValues.airport?.code || 'airport';
  steps.unshift({
    ...TIMELINE_STEPS.ARRIVE_AIRPORT,
    label: TIMELINE_STEPS.ARRIVE_AIRPORT.label.replace('{airport}', airportCode),
    timestamp: formatTime(currentTime)
  });
  
  // 8. Travel time (including buffer)
  const totalTravelTime = calculateTravelTime(formValues);
  currentTime.setMinutes(currentTime.getMinutes() - totalTravelTime);
  
  // 9. Leave home (final departure time)
  steps.unshift({
    ...TIMELINE_STEPS.LEAVE_HOME,
    timestamp: formatTime(currentTime),
    isOrigin: true
  });
  
  // Add travel duration step
  steps.splice(1, 0, {
    ...TIMELINE_STEPS.TRAVEL_TIME,
    duration: `${totalTravelTime} min`,
    breakdown: getTravelBreakdown(formValues)
  });
  
  // Calculate modifiers
  if (formValues.anxietyLevel > 0) {
    modifiers.push({
      id: 'anxiety_level',
      label: `Anxiety Level ${formValues.anxietyLevel}`,
      description: getAnxietyText(formValues.anxietyLevel, formValues.anxietyLevel * 5),
      icon: getEmoji(formValues.anxietyLevel),
      type: 'modifier'
    });
  }
  
  if (formValues.withKids) {
    modifiers.push({
      id: 'kids_buffer',
      label: 'Kids Buffer (15%)',
      description: 'Extra time added for traveling with children',
      icon: '👶',
      type: 'modifier'
    });
  }
  
  return { steps, modifiers };
}

// Helper functions for calculations
function calculateSecurityTime(formValues) {
  return 30 + // base airport buffer
    (formValues.isInternational ? 40 : 0) +
    (formValues.noTSAPre ? 15 : 0) +
    (formValues.anxietyLevel * 5);
}

function calculateTravelTime(formValues) {
  const baseTravel = parseInt(formValues.drivingTime || 0);
  const buffer = formValues.routeInfo ? 5 : 0; // TomTom buffer
  return baseTravel + buffer;
}
```

### 2. Enhanced ReceiptBreakdown Component (`src/components/ReceiptBreakdown.js`)

```javascript
import React, { useState } from "react";
import { OverlayTrigger, Tooltip } from "react-bootstrap";
import { calculateTimeline } from "../utils/timelineUtils";
import styles from "../styles/ReceiptBreakdown.module.css";

export function ReceiptBreakdown({ formValues, routeInfo, selectedDate }) {
  const [viewMode, setViewMode] = useState('timeline'); // 'timeline' or 'breakdown'
  
  const { steps, modifiers } = calculateTimeline(formValues, selectedDate);
  
  if (viewMode === 'timeline') {
    return (
      <div className={styles.receipt}>
        <div className={styles.header}>
          <h6 className={styles.receiptTitle}>Journey Timeline</h6>
          <button 
            onClick={() => setViewMode('breakdown')}
            className={styles.toggleView}
          >
            Show Breakdown
          </button>
        </div>
        
        <div className={styles.timeline}>
          {steps.map((step, index) => (
            <TimelineStep key={step.id} step={step} />
          ))}
        </div>
        
        {modifiers.length > 0 && (
          <div className={styles.modifiers}>
            <h6>Applied Modifiers:</h6>
            {modifiers.map(modifier => (
              <div key={modifier.id} className={styles.modifier}>
                <span className={styles.modifierIcon}>{modifier.icon}</span>
                <span className={styles.modifierLabel}>{modifier.label}</span>
                <span className={styles.modifierDesc}>{modifier.description}</span>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  }
  
  // Fallback to current breakdown view
  return <CurrentBreakdownView formValues={formValues} routeInfo={routeInfo} />;
}

function TimelineStep({ step }) {
  if (step.type === 'duration') {
    return (
      <div className={styles.timelineStep}>
        <div className={styles.stepDuration}>
          <span className={styles.stepIcon}>{step.icon}</span>
          <span className={styles.durationLabel}>
            {step.duration} travel time
          </span>
          {step.breakdown && (
            <div className={styles.stepBreakdown}>
              {step.breakdown.map((item, i) => (
                <div key={i} className={styles.breakdownItem}>
                  {item.label}: {item.minutes}m
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    );
  }
  
  return (
    <div className={`${styles.timelineStep} ${step.isOrigin ? styles.origin : ''} ${step.isDestination ? styles.destination : ''}`}>
      <div className={styles.stepTime}>
        {step.timestamp}
      </div>
      <div className={styles.stepContent}>
        <span className={styles.stepIcon}>{step.icon}</span>
        <span className={styles.stepLabel}>{step.label}</span>
        {step.minutes && (
          <span className={styles.stepDuration}>
            ({step.minutes}m)
          </span>
        )}
      </div>
      {step.breakdown && (
        <div className={styles.stepBreakdown}>
          {step.breakdown.map((item, i) => (
            <div key={i} className={styles.breakdownItem}>
              {item.label}: {item.minutes}m
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
```

### 3. Enhanced Styling (`src/styles/ReceiptBreakdown.module.css`)

```css
.timeline {
  position: relative;
  padding: 1rem 0;
}

.timeline::before {
  content: '';
  position: absolute;
  left: 30px;
  top: 0;
  bottom: 0;
  width: 2px;
  background: var(--border-color);
}

.timelineStep {
  position: relative;
  display: flex;
  align-items: flex-start;
  gap: 1rem;
  margin-bottom: 1.5rem;
  padding-left: 3rem;
}

.timelineStep::before {
  content: '';
  position: absolute;
  left: 24px;
  top: 6px;
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: var(--primary-color);
  border: 2px solid var(--bg-color);
}

.origin::before {
  background: var(--success-color);
}

.destination::before {
  background: var(--warning-color);
}

.stepTime {
  font-weight: 600;
  color: var(--primary-color);
  min-width: 80px;
  font-size: 0.9rem;
}

.stepContent {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  flex: 1;
}

.stepIcon {
  font-size: 1.2rem;
}

.stepLabel {
  font-weight: 500;
}

.stepDuration {
  color: var(--text-muted);
  font-size: 0.85rem;
}

.modifiers {
  margin-top: 1.5rem;
  padding-top: 1rem;
  border-top: 1px solid var(--border-color);
}

.modifier {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 0.5rem;
  font-size: 0.9rem;
}

.modifierIcon {
  font-size: 1rem;
}

.modifierLabel {
  font-weight: 500;
}

.modifierDesc {
  color: var(--text-muted);
}

.toggleView {
  background: none;
  border: 1px solid var(--border-color);
  padding: 0.25rem 0.5rem;
  border-radius: 4px;
  font-size: 0.8rem;
  cursor: pointer;
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
}
```

### 4. Update Calendar Integration (`src/utils/calendarUtils.js`)

```javascript
import { calculateTimeline } from './timelineUtils';

export function generateCalendarDescription(formValues, routeInfo, selectedDate) {
  const { steps, modifiers } = calculateTimeline(formValues, selectedDate);
  
  let description = "Airport Journey Timeline:\n\n";
  
  // Add timeline steps
  steps.forEach((step) => {
    if (step.type !== 'duration') {
      description += `${step.icon} ${step.timestamp} - ${step.label}`;
      if (step.minutes) {
        description += ` (${step.minutes}m)`;
      }
      description += "\n";
    }
  });
  
  // Add modifiers
  if (modifiers.length > 0) {
    description += "\nApplied Modifiers:\n";
    modifiers.forEach((modifier) => {
      description += `• ${modifier.label}: ${modifier.description}\n`;
    });
  }
  
  description += "\nCreated by https://airportcalc.silv.app/";
  return description;
}
```

### Phase 1: Core Timeline Logic
- [ ] Create `src/utils/timelineUtils.js` with timeline calculation functions
- [ ] Add comprehensive unit tests for timeline calculations
- [ ] Verify timeline logic matches current calculation results

### Phase 2: Component Enhancement  
- [ ] Refactor `ReceiptBreakdown.js` to support timeline view
- [ ] Add timeline/breakdown view toggle
- [ ] Create responsive timeline styling
- [ ] Ensure accessibility (screen readers, keyboard navigation)

### Phase 3: Integration & Polish
- [ ] Update calendar integration to use timeline format
- [ ] Add timeline support to plain text breakdown
- [ ] Test across different form configurations
- [ ] Verify mobile responsiveness

### Phase 4: Testing & Documentation
- [ ] Add comprehensive component tests
- [ ] Test with various timezone configurations  
- [ ] Update documentation with new timeline feature
- [ ] Performance testing with complex timelines

## Design Considerations

**Modularity:** Keep timeline logic separate from display logic for maintainability

**Flexibility:** Support both timeline and breakdown views for user preference

**Accessibility:** Ensure timeline is readable by screen readers and keyboard navigable

**Performance:** Optimize timeline calculations for real-time updates

**Mobile:** Design timeline to work well on small screens with horizontal scrolling if needed

## Success Criteria

- [ ] Timeline shows logical progression from leave time to boarding
- [ ] All current calculation features work in timeline format
- [ ] Plain text version (calendar) includes timeline information  
- [ ] Component maintains performance with complex configurations
- [ ] UI is intuitive and improves user understanding of timing
